# Generated by Django 3.1.7 on 2021-03-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gender', models.CharField(max_length=5)),
                ('age', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('category', models.TextField()),
                ('avatar', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
