# Generated by Django 3.1.7 on 2021-03-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0002_blogger_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogger',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='blogger',
            name='lname',
            field=models.TextField(default=' '),
        ),
    ]
