# Generated by Django 3.1.7 on 2021-03-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0003_auto_20210307_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media\\pics'),
        ),
    ]
