# Generated by Django 3.1.7 on 2021-04-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0004_auto_20210309_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='username',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
