# Generated by Django 3.1.7 on 2021-04-24 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0005_auto_20210423_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likedby', models.TextField(default=' ')),
                ('blogliked', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogposts.blogger')),
            ],
        ),
    ]
