# Generated by Django 3.1.7 on 2021-04-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0006_auto_20210424_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
